kind: pipeline
type: docker
name: linux-x64

steps:
- name: build
  image: electronuserland/builder
  volumes:
  - name: cache
    path: /drone/src/electron-builder
  - name: cache-builder
    path: /drone/src/electron
  - name: release
    path: /drone/src/release
  commands:
  - yarn
  - yarn build:linux

volumes:
- name: cache
  host:
    path: /tmp/cache/electron
- name: cache-builder
  host:
    path: /tmp/cache/electron-builder
- name: release
  host:
    path: /var/starlight/release
---
kind: pipeline
type: docker
name: windows-x64

steps:
- name: build
  image: electronuserland/builder:wine
  volumes:
  - name: cache
    path: /drone/src/.cache/electron-builder
  - name: cache-builder
    path: /drone/src/.cache/electron
  - name: release
    path: /drone/src/release
  commands:
  - yarn
  - yarn build:win32

volumes:
- name: cache
  host:
    path: /tmp/cache/electron
- name: cache-builder
  host:
    path: /tmp/cache/electron-builder
- name: release
  host:
    path: /var/starlight/release